// ===========================================================================
// LocalIQ — Simulated Experience Database (Mumbai Pilot)
// ===========================================================================
// NOTE FOR JUDGES / ARCHITECTS:
// This is a client-side mock simulating our planned production data layer:
//
// Planned Production Architecture:
//   React Frontend
//     ↓ (JSON over HTTP / WebSocket)
//   FastAPI Gateway (Python 3.11+, Pydantic v2 schemas)
//     ├── PostgreSQL (Relational schema: venues, hours, prices, coordinates, accessibility)
//     ├── Qdrant Vector DB (768-dim embeddings for intent & vibe query matching)
//     └── Live Context Connectors:
//           ├── Google Places API (live operating hours, busy times, review summaries)
//           ├── Google Maps/Routes API (real-time multimodal transit matrices with live delay buffers)
//           └── Open-Meteo API (hourly precipitation radar, rain probability, wind, UV index)
// ===========================================================================

export const INTERESTS = [
  "Food",
  "Culture",
  "History",
  "Shopping",
  "Nature",
  "Art",
  "Local Life",
  "Adventure",
];

export const GROUPS = ["Solo", "Couple", "Friends", "Family"];

export const ACCESSIBILITY_OPTIONS = [
  { value: "any", label: "Any route" },
  { value: "easy_walking", label: "Easy walking" },
  { value: "wheelchair", label: "Wheelchair friendly" },
  { value: "low_walking", label: "Low walking" },
];

export const TIME_OPTIONS = [60, 90, 120, 150, 180];

export const timeLabel = (min) => {
  if (min % 60 === 0) return `${min / 60} ${min === 60 ? "hour" : "hours"}`;
  const h = Math.floor(min / 60);
  const m = min % 60;
  return h > 0 ? `${h}h ${m}m` : `${m} min`;
};

export const EXPERIENCES = [
  {
    id: "e1",
    name: "Kala Ghoda Art Walk",
    category: "Culture · Local Gem",
    area: "Kala Ghoda, Fort",
    location: "Fort, Mumbai",
    mapX: 205,
    mapY: 215,
    price: 0,
    duration: 70,
    travelTime: 18,
    rating: 4.7,
    reviews: 1240,
    isOpen: true,
    openingHours: "10:00 – 21:00",
    isIndoor: false,
    weatherType: "both", // covered colonnades & tree canopy; rain-viable
    localScore: 90,
    touristScore: 55,
    interests: ["Culture", "Art", "History"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking"],
    art: "gallery",
    image: "/images/kala_ghoda.jpg",
    tagline:
      "A guided stroll past street art, heritage lanes and sheltered book corners.",
    description:
      "Wander Mumbai's gallery quarter with a local storyteller: vibrant street murals, century-old Victorian stone facades, independent art bookstores and sheltered porticos that protect you from the drizzle.",
    bestTime: "Late afternoon, sheltered lanes",
    safetyNote: null,
  },
  {
    id: "e2",
    name: "Irani Café Trail",
    category: "Food · Local Experience",
    area: "Bastion, Fort",
    location: "Fort, Mumbai",
    mapX: 210,
    mapY: 240,
    price: 450,
    duration: 40,
    travelTime: 9,
    rating: 4.8,
    reviews: 890,
    isOpen: true,
    openingHours: "07:00 – 22:00",
    isIndoor: true,
    weatherType: "indoor",
    localScore: 95,
    touristScore: 50,
    interests: ["Food", "Culture", "Local Life"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking", "low_walking"],
    art: "cafe",
    image: "/images/irani_cafe.jpg",
    tagline:
      "Bun maska, steaming cutting chai and century-old nostalgic charm.",
    description:
      "Cozy up inside heritage Parsi cafés for piping hot Irani chai, crusty bun-maska dipped in sweet tea, and fragrant berry pulao — the quintessential rainy afternoon haven in old Bombay.",
    bestTime: "Ideal refuge on a rainy afternoon",
    safetyNote: null,
  },
  {
    id: "e3",
    name: "CSMVS Museum + Heritage Wing",
    category: "History · Culture",
    area: "Kala Ghoda, Fort",
    location: "Fort, Mumbai",
    mapX: 185,
    mapY: 285,
    price: 300,
    duration: 90,
    travelTime: 25,
    rating: 4.8,
    reviews: 2100,
    isOpen: true,
    openingHours: "10:15 – 17:30",
    isIndoor: true,
    weatherType: "indoor",
    localScore: 70,
    touristScore: 75,
    interests: ["History", "Culture", "Art"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking", "wheelchair"],
    art: "museum",
    image: "/images/csmvs_museum.jpg",
    tagline:
      "Rare sculptures, miniature paintings and grand Indo-Saracenic galleries.",
    description:
      "One of India's premier cultural institutions: 70,000 artefacts across archaeology, art, and natural history housed beneath a magnificent heritage dome. Requires at least 90 minutes to experience properly.",
    bestTime: "Perfect for rainy days when you have 2.5h+",
    safetyNote: null,
  },
  {
    id: "e4",
    name: "Chor Bazaar Antique Hunt",
    category: "Shopping · Local Gem",
    area: "Mumbadevi",
    location: "South Mumbai",
    mapX: 195,
    mapY: 195,
    price: 200,
    duration: 75,
    travelTime: 28,
    rating: 4.4,
    reviews: 640,
    isOpen: true,
    openingHours: "11:00 – 19:30",
    isIndoor: false,
    weatherType: "both",
    localScore: 88,
    touristScore: 60,
    interests: ["Shopping", "Local Life", "History"],
    groupFit: ["Couple", "Friends"],
    accessibility: ["easy_walking"],
    art: "market",
    image: "/images/chor_bazaar.jpg",
    tagline:
      "Vintage gramophones, Bollywood posters and brass curios in a 150-year-old market.",
    description:
      "A treasure hunt through one of Asia's largest flea and antique bazaars: retro vinyl, movie memorabilia, vintage clocks and brass lamps with sellers who've traded here for three generations.",
    bestTime: "Weekday afternoons, requires 2+ hours",
    safetyNote: "Covered shop fronts, but carry an umbrella between alleyways",
  },
  {
    id: "e5",
    name: "Colaba Causeway Food & Market",
    category: "Food · Shopping",
    area: "Colaba",
    location: "Colaba, Mumbai",
    mapX: 170,
    mapY: 305,
    price: 350,
    duration: 60,
    travelTime: 18,
    rating: 4.5,
    reviews: 1520,
    isOpen: true,
    openingHours: "09:00 – 22:00",
    isIndoor: false,
    weatherType: "both", // covered street arcades
    localScore: 80,
    touristScore: 70,
    interests: ["Food", "Shopping", "Local Life"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking"],
    art: "food",
    image: "/images/colaba_causeway.jpg",
    tagline:
      "Kebabs, cutting chai and lively covered street bazaars in South Mumbai.",
    description:
      "Graze down Causeway beneath sheltering heritage awnings: warm kathi rolls, steaming street snacks, handicrafts and old cafes like Leopold, ending near the harbour.",
    bestTime: "Evenings and sheltered rainy afternoons",
    safetyNote: null,
  },
  {
    id: "e6",
    name: "Gateway of India + Waterfront",
    category: "Landmark · Tourist Highlight",
    area: "Apollo Bunder, Colaba",
    location: "Colaba, Mumbai",
    mapX: 150,
    mapY: 330,
    price: 0,
    duration: 45,
    travelTime: 22,
    rating: 4.6,
    reviews: 4200,
    isOpen: true,
    openingHours: "Open all day",
    isIndoor: false,
    weatherType: "outdoor",
    localScore: 45,
    touristScore: 95,
    interests: ["History", "Culture", "Nature"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking", "wheelchair"],
    art: "landmark",
    image: "/images/gateway_of_india.jpg",
    tagline:
      "Mumbai's iconic basalt archway overlooking the Arabian Sea harbour.",
    description:
      "The 26-metre triumphal basalt arch standing at the water's edge. Ferries rock gently at the quay with pigeons circling against sea winds.",
    bestTime: "Clear sunny mornings & golden hours",
    safetyNote: "Waterfront pier is slick and ferries are restricted during active monsoon rain",
  },
  {
    id: "e7",
    name: "Marine Drive Promenade",
    category: "Nature · Iconic",
    area: "Marine Drive",
    location: "South Mumbai",
    mapX: 128,
    mapY: 165,
    price: 0,
    duration: 40,
    travelTime: 15,
    rating: 4.8,
    reviews: 3800,
    isOpen: true,
    openingHours: "Open all day",
    isIndoor: false,
    weatherType: "outdoor",
    localScore: 60,
    touristScore: 90,
    interests: ["Nature", "Local Life", "Culture"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking", "wheelchair"],
    art: "seafront",
    image: "/images/marine_drive.jpg",
    tagline:
      "The Queen's Necklace — sweeping Arabian sea views and coastal breeze.",
    description:
      "A 3-kilometer curved coastal boulevard facing the open Arabian Sea. Magical on clear days and golden evenings; completely unsheltered during heavy monsoon downpours.",
    bestTime: "Clear evenings and breezy sunsets",
    safetyNote: "Unsheltered sea wall with high waves during monsoon rains",
  },
  {
    id: "e8",
    name: "Dr. Bhau Daji Lad Museum",
    category: "Culture · Heritage",
    area: "Byculla",
    location: "Byculla, Mumbai",
    mapX: 250,
    mapY: 150,
    price: 150,
    duration: 80,
    travelTime: 30,
    rating: 4.7,
    reviews: 980,
    isOpen: true,
    openingHours: "10:00 – 18:00",
    isIndoor: true,
    weatherType: "indoor",
    localScore: 85,
    touristScore: 65,
    interests: ["Culture", "History", "Art"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking", "wheelchair"],
    art: "heritage",
    image: "/images/bhau_daji_lad.jpg",
    tagline:
      "Mumbai's oldest museum inside an exquisite Victorian mint-green palace.",
    description:
      "Gilded Victorian arches, crystal chandeliers, miniature clay dioramas of 19th-century communities, and tranquil botanical surroundings. A quiet architectural masterpiece.",
    bestTime: "Quiet indoor afternoon, requires 2.5h+",
    safetyNote: null,
  },
  {
    id: "e9",
    name: "Jehangir Art Gallery",
    category: "Art · Local Gem",
    area: "Fort",
    location: "Fort, Mumbai",
    mapX: 212,
    mapY: 222,
    price: 10,
    duration: 35,
    travelTime: 10,
    rating: 4.6,
    reviews: 710,
    isOpen: true,
    openingHours: "11:00 – 19:00",
    isIndoor: true,
    weatherType: "indoor",
    localScore: 88,
    touristScore: 58,
    interests: ["Art", "Culture"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking"],
    art: "art",
    image: "/images/jehangir_art.jpg",
    tagline:
      "Contemporary Indian artwork and sculptures right in the heart of Kala Ghoda.",
    description:
      "Rotating exhibitions from emerging and established Indian artists across three modernist halls, plus a heritage café next door for quick filter coffee. Fast, close, and completely indoor.",
    bestTime: "Anytime — fast 35-min indoor visit",
    safetyNote: null,
  },
  {
    id: "e10",
    name: "Sassoon Dock Fish Auction",
    category: "Local Life · Photography",
    area: "Colaba Docks",
    location: "Colaba, Mumbai",
    mapX: 142,
    mapY: 318,
    price: 100,
    duration: 50,
    travelTime: 32,
    rating: 4.3,
    reviews: 460,
    isOpen: false, // Dawn-only schedule: 05:00 - 11:00
    openingHours: "05:00 – 11:00 (Closed right now)",
    isIndoor: false,
    weatherType: "outdoor",
    localScore: 92,
    touristScore: 62,
    interests: ["Local Life", "Food", "Nature"],
    groupFit: ["Solo", "Couple", "Friends"],
    accessibility: ["easy_walking"],
    art: "docks",
    image: "/images/sassoon_dock.jpg",
    tagline:
      "Historic morning fish market and colourful Koli fishing boats at dawn.",
    description:
      "Hundreds of colourful wooden fishing trawlers unloading their morning haul of Bombay Duck and tiger prawns. A chaotic, vibrant spectacle that closes by late morning.",
    bestTime: "Early dawn only (05:30 – 09:30 AM)",
    safetyNote: "Closed right now for the afternoon session",
  },
  {
    id: "e11",
    name: "Prithvi Café & Theatre",
    category: "Culture · Food",
    area: "Juhu",
    location: "Juhu, Mumbai",
    mapX: 105,
    mapY: 30,
    price: 600,
    duration: 75,
    travelTime: 40,
    rating: 4.7,
    reviews: 1350,
    isOpen: false, // Opens at 15:00, currently 14:00 in demo
    openingHours: "15:00 – 23:30 (Opens at 3:00 PM)",
    isIndoor: true,
    weatherType: "indoor",
    localScore: 78,
    touristScore: 70,
    interests: ["Culture", "Food", "Art"],
    groupFit: ["Couple", "Friends", "Family"],
    accessibility: ["easy_walking"],
    art: "cafe",
    image: "/images/prithvi_cafe.jpg",
    tagline:
      "Mumbai's beloved cultural adda for Irish coffee, parathas and theatre buzz.",
    description:
      "Leafy open courtyard under bamboo groves with hanging lanterns, literary discussions and actors rehearsing lines. Located in northern Juhu; opens at 3:00 PM.",
    bestTime: "Evenings after 4:00 PM",
    safetyNote: "Venue opens at 3:00 PM (currently closed)",
  },
  {
    id: "e12",
    name: "Mani Bhavan Gandhi Museum",
    category: "History · Indoor",
    area: "Gamdevi",
    location: "Gamdevi, Mumbai",
    mapX: 165,
    mapY: 165,
    price: 10,
    duration: 55,
    travelTime: 25,
    rating: 4.6,
    reviews: 830,
    isOpen: true,
    openingHours: "09:30 – 18:00",
    isIndoor: true,
    weatherType: "indoor",
    localScore: 82,
    touristScore: 60,
    interests: ["History", "Culture"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking", "wheelchair"],
    art: "heritage",
    image: "/images/mani_bhavan.jpg",
    tagline:
      "Where Mahatma Gandhi lived and worked — a tranquil heritage house museum.",
    description:
      "Teakwood bookshelves, personal letters, spinning charkhas, and the preserved room where major satyagraha movements were conceived. Peaceful, historic, and entirely indoors.",
    bestTime: "Indoor heritage — all weather",
    safetyNote: null,
  },
  {
    id: "e13",
    name: "Haji Ali Dargah + Causeway",
    category: "Culture · Landmark",
    area: "Worli",
    location: "Worli, Mumbai",
    mapX: 100,
    mapY: 200,
    price: 0,
    duration: 60,
    travelTime: 24,
    rating: 4.5,
    reviews: 1900,
    isOpen: true,
    openingHours: "06:00 – 22:00",
    isIndoor: false,
    weatherType: "outdoor",
    localScore: 70,
    touristScore: 82,
    interests: ["Culture", "History"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking"],
    art: "landmark",
    image: "/images/haji_ali.jpg",
    tagline:
      "White marble Indo-Islamic sanctuary perched on an islet in the ocean.",
    description:
      "A 600-year-old sanctuary surrounded by the Arabian Sea, linked by a 500-metre stone walkway. Requires low tide and calm seas for comfortable access.",
    bestTime: "Low tide on clear sunny afternoons",
    safetyNote: "Causeway is submerged or washed by high waves during active monsoon weather",
  },
  {
    id: "e14",
    name: "Jio World Plaza — BKC",
    category: "Shopping · Modern",
    area: "Bandra Kurla Complex",
    location: "BKC, Mumbai",
    mapX: 300,
    mapY: 60,
    price: 800,
    duration: 90,
    travelTime: 35,
    rating: 4.2,
    reviews: 1200,
    isOpen: true,
    openingHours: "11:00 – 22:00",
    isIndoor: true,
    weatherType: "indoor",
    localScore: 35,
    touristScore: 88,
    interests: ["Shopping", "Food", "Adventure"],
    groupFit: ["Friends", "Family", "Couple"],
    accessibility: ["easy_walking", "wheelchair", "low_walking"],
    art: "mall",
    image: null,
    tagline:
      "Ultra-modern luxury retail, art installations and gourmet dining in BKC.",
    description:
      "Mumbai's newest luxury retail and lifestyle destination: high-end fashion, contemporary indoor art, and multi-cuisine cafes across an expansive air-conditioned atrium.",
    bestTime: "Indoor shopping — ideal for 3h+ excursions",
    safetyNote: null,
  },
  {
    id: "e15",
    name: "Worli Sea Face Promenade",
    category: "Nature · Iconic",
    area: "Worli",
    location: "Worli, Mumbai",
    mapX: 92,
    mapY: 120,
    price: 0,
    duration: 35,
    travelTime: 26,
    rating: 4.6,
    reviews: 2600,
    isOpen: true,
    openingHours: "Open all day",
    isIndoor: false,
    weatherType: "outdoor",
    localScore: 65,
    touristScore: 85,
    interests: ["Nature", "Local Life"],
    groupFit: ["Solo", "Couple", "Friends", "Family"],
    accessibility: ["easy_walking"],
    art: "seafront",
    image: "/images/marine_drive.jpg",
    tagline:
      "Dramatic sea breezes and panoramic views of the Bandra-Worli Sea Link.",
    description:
      "A wide seaside promenade stretching along the bay with direct views of the cable-stayed Sea Link bridge. Best walked during calm coastal weather.",
    bestTime: "Clear evenings with sea breeze",
    safetyNote: "Direct sea spray and open to rain during downpours",
  },
];

export const QUICK_PROMPTS = [
  {
    label: "2 hours · ₹1000 · Rain (Seeded)",
    icon: "rain",
    apply: { time: 120, budget: 1000, weather: "rain", interests: ["Culture", "Food"] },
  },
  {
    label: "Quick 1 Hour · ₹500",
    icon: "clock",
    apply: { time: 60, budget: 500, weather: "rain", interests: ["Culture", "Food"] },
  },
  {
    label: "Sunny afternoon · 3 hours",
    icon: "gem",
    apply: { time: 180, budget: 1200, weather: "sunny", interests: ["Culture", "History", "Nature"] },
  },
  {
    label: "Local food gems · Evening",
    icon: "food",
    apply: { time: 120, budget: 700, weather: "rain", interests: ["Food", "Local Life"] },
  },
  {
    label: "Family friendly · Sunny",
    icon: "family",
    apply: { time: 150, budget: 1500, weather: "sunny", interests: ["Culture", "Nature"], group: "Family" },
  },
];

export const EXPERIENCE_BY_ID = Object.fromEntries(
  EXPERIENCES.map((e) => [e.id, e])
);

export const DEFAULT_QUERY =
  "I have 2 hours in Mumbai, ₹1000 budget, and want something local and indoors.";

export const VOICE_QUERY =
  "Find something local and indoor for 2 hours under ₹700.";